### ISSUE TITLE
Nicer reporting of missing indices

### ISSUE THREAD

**Issue by obo** [ELITR/SLTev#16]
Asking for a non-existing index file returns:

```
Cloning into 'elitr-testset'...
remote: Enumerating objects: 173, done.
remote: Counting objects: 100% (173/173), done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 5288 (delta 93), reused 135 (delta 70), pack-reused 5115
Receiving objects: 100% (5288/5288), 1.36 GiB | 27.70 MiB/s, done.
Resolving deltas: 100% (1638/1638), done.
Checking out files: 100% (1730/1730), done.
Your branch is up to date with 'origin/master'.
Traceback (most recent call last):
  File "SLTev-scripts/SLTev", line 97, in <module>
    populate(indice_file_path, target_path)
  File "/lnet/spec/work/people/bojar/diplomka/granty/elitr/testing-sltev-20210119-1446/SLTev/SLTev-scripts/utilities.py", line 43, in populate
    with open(indice_file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: './elitr-testset/indices/auto-mt'
```
The last part should be custom, nicer; ideally listing all available indices.

**Comment by mohammad2928** [comment]
It's done.
