### ISSUE TITLE
broken pipe error in the demo

### ISSUE THREAD

**Issue by obo** [ELITR/SLTev#18]
I followed the instructions to evaluate one file of Khan Academy (with a freshly obtained SLTev, running from the directories as expected) and I got this broken pipe error.

```
(venv) 15:59 victoria SLTev-scripts$./SLTev -e khanacademy-for-SLTev -i ../examples/slt-asr-samples/kaccNlwi6lUCEM.en.cs.slt
Evaluating the file ../examples/slt-asr-samples/kaccNlwi6lUCEM.en.cs.slt in terms of translation quality against ./SLTev-cache/OStt-tt-files/khanacademy-for-SLTev/kaccNlwi6lUCEM.en.TTcs
commit id is  d798cc9de325ab8019b8b02cebcf6a9fb9e9f929
Traceback (most recent call last):
  File "evaluator.py", line 88, in <module>
    references.append(read_tt(path))
  File "/lnet/spec/work/people/bojar/diplomka/granty/elitr/testing-sltev-20210119-1446/SLTev/SLTev-scripts/files_modules.py", line 66, in read_tt
    l = tokenize(line.strip())
  File "/lnet/spec/work/people/bojar/diplomka/granty/elitr/testing-sltev-20210119-1446/SLTev/venv/lib/python3.6/site-packages/mosestokenizer/tokenizer.py", line 70, in __call__
    self.writeline(sentence)
  File "/lnet/spec/work/people/bojar/diplomka/granty/elitr/testing-sltev-20210119-1446/SLTev/venv/lib/python3.6/site-packages/toolwrapper.py", line 141, in writeline
    self.stdin.write(line + "\n")
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <bound method ToolWrapper.__del__ of mosestokenizer.tokenizer.MosesTokenizer(['perl', '/lnet/spec/work/people/bojar/diplomka/granty/elitr/testing-sltev-20210119-1446/SLTev/venv/lib/python3.6/site-packages/mosestokenizer/tokenizer-v1.1.perl', '-q', '-l', 'en', '-b', '-a'], encoding='utf-8', cwd=None)>
Traceback (most recent call last):
  File "/lnet/spec/work/people/bojar/diplomka/granty/elitr/testing-sltev-20210119-1446/SLTev/venv/lib/python3.6/site-packages/toolwrapper.py", line 67, in __del__
    self.close()
  File "/lnet/spec/work/people/bojar/diplomka/granty/elitr/testing-sltev-20210119-1446/SLTev/venv/lib/python3.6/site-packages/toolwrapper.py", line 133, in close
    getattr(self, attr).close()
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by obo** [comment]
To be solved in #22, same bug.
